source "https://rubygems.org"

ruby "3.2.6"

gem "rails", "~> 7.1.0"
gem "mysql2", "~> 0.5"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "bcrypt", "~> 3.1"
gem "jwt", "~> 2.8"
gem "rack-cors"
gem "image_processing", "~> 1.2"
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
end
